package com.github.danrog303.cbzutilities.actions
import com.github.danrog303.cbzutilities.models.ComicInfo
import com.github.danrog303.cbzutilities.packing.CbzPacker
import com.github.danrog303.cbzutilities.unpacking.CbzUnpacker

/**
 * Extracts content of **args.input** cbz file to **args.output** directory.
 * @param args Parsed console arguments generated by main function
 */
class ExtractAction(private val args: Map<String, Any>): Runnable {
    override fun run() {
        val unpacker = CbzUnpacker(args["input"].toString(), args["output"].toString())
        unpacker.unpack()
    }
}
